apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cosmos-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: cosmos-credentials
      type: Opaque
      data:
        - objectName: cosmos-primary-key
          key: primary-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyvault.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.keyvault.name | quote }}
    tenantId: {{ .Values.keyvault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: cosmos-primary-key
          objectType: secret
