apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestration-ui-ingress
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.ui.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ui.className }}
  {{ if ne .Values.ingress.ui.host "" }}
  tls:
    - hosts:
        - {{ .Values.ingress.ui.host }}
      secretName: ui-tls-secret
  rules:
    - host: {{ .Values.ingress.ui.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orchestration-ui-service
                port:
                  number: 80
  {{ else }}
  rules:
    - host: {{ .Values.staticIPs.orchestrationUI }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orchestration-ui-service
                port:
                  number: 80
  {{ end }}