apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pg-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: pg-admin-password
          key: password
        - objectName: pg-admin-username
          key: username
        - objectName: pg-hub-url
          key: hub-url
        - objectName: pg-ui-url
          key: ui-url
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyvault.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.keyvault.name | quote }}
    tenantId: {{ .Values.keyvault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: pg-admin-password
          objectType: secret
        - |
          objectName: pg-admin-username
          objectType: secret
        - |
          objectName: pg-hub-url
          objectType: secret
        - |
          objectName: pg-ui-url
          objectType: secret