apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: zipline-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: cosmos-credentials
      type: Opaque
      data:
        - objectName: cosmos-primary-key
          key: primary-key
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: pg-admin-password
          key: password
        - objectName: pg-admin-username
          key: username
    {{ if .Values.kyuubi.credentials.enabled }}
    - secretName: kyuubi-credentials
      type: Opaque
      data:
        - objectName: {{ .Values.kyuubi.credentials.username_secret }}
          key: username
        - objectName: {{ .Values.kyuubi.credentials.password_secret }}
          key: password
    {{ end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyvault.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.keyvault.name | quote }}
    tenantId: {{ .Values.keyvault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: cosmos-primary-key
          objectType: secret
        - |
          objectName: pg-admin-password
          objectType: secret
        - |
          objectName: pg-admin-username
          objectType: secret
        {{ if .Values.kyuubi.credentials.enabled }}
        - |
          objectName: {{ .Values.kyuubi.credentials.username_secret }}
          objectType: secret
        - |
          objectName: {{ .Values.kyuubi.credentials.password_secret }}
          objectType: secret
        {{ end }}